### ISSUE TITLE
ERROR render of "section" failed: execute of template failed

### ISSUE THREAD

**Issue by WeyardWiz** [sfrisk/webcomics-cms#25]
```
C:\Hugo\Sites\webcomics-cms>hugo serve -D
Start building sites …
hugo v0.84.1-4BD65E22+extended windows/amd64 BuildDate=2021-06-24T11:44:23Z VendorInfo=gohugoio
ERROR 2021/06/27 17:13:54 render of "section" failed: execute of template failed: template: comic/list.html:3:5: executing "comic/list.html" at <partial "head.html" .>: error calling partial: "C:\Hugo\Sites\webcomics-cms\themes\webcomic\layouts\partials\head.html:14:96": execute of template failed: template: partials/head.html:14:96: executing "partials/head.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type
ERROR 2021/06/27 17:13:54 render of "section" failed: execute of template failed: template: news/list.html:3:5: executing "news/list.html" at <partial "head.html" .>: error calling partial: "C:\Hugo\Sites\webcomics-cms\themes\webcomic\layouts\partials\head.html:14:96": execute of template failed: template: partials/head.html:14:96: executing "partials/head.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type
ERROR 2021/06/27 17:13:54 render of "section" failed: execute of template failed: template: comic/list.html:3:5: executing "comic/list.html" at <partial "head.html" .>: error calling partial: "C:\Hugo\Sites\webcomics-cms\themes\webcomic\layouts\partials\head.html:14:96": execute of template failed: template: partials/head.html:14:96: executing "partials/head.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type
ERROR 2021/06/27 17:13:54 render of "section" failed: execute of template failed: template: comic/list.html:3:5: executing "comic/list.html" at <partial "head.html" .>: error calling partial: "C:\Hugo\Sites\webcomics-cms\themes\webcomic\layouts\partials\head.html:14:96": execute of template failed: template: partials/head.html:14:96: executing "partials/head.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type
Built in 169 ms
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:3:5: executing "index.html" at <partial "head.html" .>: error calling partial: "C:\Hugo\Sites\webcomics-cms\themes\webcomic\layouts\partials\head.html:14:96": execute of template failed: template: partials/head.html:14:96: executing "partials/head.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type
```

**Comment by WeyardWiz** [comment]
ok so according to [this](https://gitmemory.com/issue/jakewies/hugo-theme-codex/165/808673930) post, I removed this line from **_C:\Hugo\Sites\webcomics-cms\themes\webcomic\layouts\partials\head.html_**

`{{ printf `<link rel="%s" type="%s+%s" href="%s" title="%s" />` .Rel .MediaType.Type .MediaType.Suffix .Permalink $.Site.Title | safeHTML }}`

and the serve then worked!

I actually undid that change, and then just removed `.MediaType.Suffix` and even that worked.

But idk if that line is needed for something...i was able to launch the site just fine though without it...

**Comment by benafischer94** [comment]
It looks like in Hugo .82 they moved .MediaType.Suffix to .MediaType.Suffixes
So if you change it to:

`{{ printf .Rel .MediaType.Type .MediaType.Suffixes .Permalink $.Site.Title | safeHTML }}`

it will work again.

This can be useful for doing different rendering based on content type. Per the Original documentation [here](https://gohugo.io/templates/output-formats/#:~:text=Suffixes%20are%20the%20values%20that%20will%20be%20used,make%20sure%20they%20are%20recognized%20by%20the%20browser.).

Some additional context on what the [properties](https://gohugo.io/content-management/page-resources/#properties) do. Note that MediaTypes.Suffixes is at the bottom.

I think originally the thought was only serve the most common suffix for the file type. Then to allow granularity on the different extensions a file type can use prompted the change to providing the full list.

**Comment by sfrisk** [comment]
Apparently I turned off my email notifications for github, so only just seeing this.  I'll look at this this evening and make sure everything works with latest version of hugo with directions.

**Comment by sfrisk** [comment]
Okay, I've updated this repo to use Hugo 0.91.2 instead of Hugo 0.57.2 (which is what Netlify was configured to use).  I've updated the readme to show the supported version of Hugo as well.
