### ISSUE TITLE
No License, but I would like to know if I can use it

### ISSUE THREAD

**Issue by Melvillian** [sfrisk/webcomics-cms#26]
Hi Sarah,

I would like to build a website for my girlfriend so she can host her own comics on it. I found this repo while searching online, but I am hesitant to use it since you do not have a license.

Can you add a license (preferably something that allows others to use and modify your code) so that it's clear you are OK with me using your code?

To be clear, I intend to fork this repo, modify the layout and design to fit my gf's daily diary comics + other fiction work, and then host that on her own domain.

Thanks!

**Comment by sfrisk** [comment]
Hey! Just saw this, I am totally okay with people using this code (or modifying it) for their own projects, this project was made mostly as an example/learning tool of how you could do stuff out of a more formal CMS system.  I'll get up a license today!

**Comment by sfrisk** [comment]
License added!
